### PR TITLE
feature: Privilege providers

### PR DESCRIPTION
**Pull request by martintc**
## I'm submitting a

- [ ] bug fix
- [x] feature
- [ ] documentation addition

## What is the current behaviour?

Comtrya also utilizes `sudo` for privilege escalation.

## What is the expected behavior?

Add the ability to specify a provider for privilege escalation with the initial offering of using `doas` as a privilege provider.

## What is the motivation / use case for changing the behavior?

Issue #429 

## Please tell us about your environment:

Version (`comtrya --version`): 0.8.9
Operating system: macOS 15.0

### CODE REVIEW

**Comment by martintc** [comment]
This is a pretty early rough draft, it still needs clean up. I am placing a draft here for anyone who wishes to test this and have input while I still clean up and play with the code.

To use this, you will need a `Comtrya.yaml` file with your manifests.

The `Comtrya.yaml` file will need this in there, in order to use doas.

```yaml
privilege: doas
```

If you want to specify using sudo:

```yaml
privilege: sudo
```

However, `sudo` is *default*. So if none is specified, comtrya will use `sudo`. 

Another note that I need help testing. I had some issues with getting the password prompt for `doas` and was only able to get it work, configuring `nopass` for my user in doas. I would like a verification of that. Possibly also some input from `doas` users to know if this is fine. I see often that people configure their user for `nopass` in the `doas.conf` file.

**Comment by martintc** [comment]
@yonas Here is a branch with a draft PR if you would like to test this. If you need more instructions, let me know. There are some above this comment.

**Comment by yonas** [comment]
@martintc Thanks, this worked for me.

> Another note that I need help testing. I had some issues with getting the password prompt for doas and was only able to get it work, 

I can't reproduce this. I get a password prompt without `nopass`, and no password prompt when it's present.

**Comment by yonas** [comment]
My only suggestion is to add some auto-detect logic so that non-default options like `doas` are used if the default `sudo` isn't installed.

**Comment by martintc** [comment]
> @martintc Thanks, this worked for me.
> 
> > Another note that I need help testing. I had some issues with getting the password prompt for doas and was only able to get it work,
> 
> I can't reproduce this. I get a password prompt without `nopass`, and no password prompt when it's present.

It could just be my system and having compiled opendoas for it to work on macOS, haha. I'd try it on my BSD machine, but I am currently out of town, so no access to it.

**Comment by martintc** [comment]
Update for those watching. What else is lefts:

1. Adding in the code for privilege providers to package actions.
2. Fix tests on other platforms, this is fairly easy and straight forward.

**Pull request merged**
