### PR TITLE
feat: implement already installed query for provider yay

### LINKED ISSUE #136: yay/pacman provider - should be able to filter packages with `query`
Hi, 

I recently moved my dotfiles to comtrya and I'm using the yay/pacman provider to provision packages.

Important bit of information is I don't just use the setup to bootstrap on a new machine, but I use it to change things too. So for example if I find a new useful tool (like `s-tui`) I will not manually install the package but instead put it in my manifest and run comtrya. This way, my manifest is always up-to-date with what I want.

I noticed that the yay cmdline does not set the `--needed` flag which results in very long manifest execution because it reinstalls all pacman packages. Would it be ok to add the flag or is there a reason it's not included?

Note: this flag does not work for AUR packages, unfortunately: https://github.com/Jguer/yay/issues/885
But it does work for regular packages. Here's an example (first without --neeed and then with):

```bash
» yay -S --noconfirm --nocleanmenu --nodiffmenu acpi
warning: acpi-1.7-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) acpi-1.7-3

Total Installed Size:  0.03 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                      [#####################################################################] 100%
(1/1) checking package integrity                                                                                    [#####################################################################] 100%
(1/1) loading package files                                                                                         [#####################################################################] 100%
(1/1) checking for file conflicts                                                                                   [#####################################################################] 100%
(1/1) checking available disk space                                                                                 [#####################################################################] 100%
:: Processing package changes...
(1/1) reinstalling acpi                                                                                             [#####################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

» yay -S --noconfirm --nocleanmenu --nodiffmenu acpi --needed
warning: acpi-1.7-3 is up to date -- skipping
 there is nothing to do
```

For AUR packages I have a hacky solution with koto where I write to a file so the installation is only performed the first time.

### PR DESCRIPTION
**Pull request by mriehl**
Resolves #136

-Qq with package list is chosen for efficiency (no need to query each
package individually)

There is a bit sad edge case where you can request installation of
something like `pkg-config` but the package is actually called
`pkgconf` where this will fail to detect already installed. But the
"fix" is simply to add the proper package name :)
I don't see a way of solving this without shelling out for each
package individually or saving all the package aliases.

### CODE REVIEW

**Comment by mriehl** [comment]
Maybe you have an idea to test this @rawkode ... I can probably mock the Process API and assert on the Steps that are returned from calling `install`?

**Comment by rawkode** [comment]
@mriehl It's really painful to test an `Action` at the moment because they require a `Manifest` and `Contexts` - I actually just did this myself on PR #141 and I hated everything about it.

I'll look at providing some helpers for this, but for now it's OK.

I see that you've tested this with your own dotfiles, soo you're confident and happy it works?

**Comment by rawkode** [comment]
@mriehl Looks like you need to run `cargo fmt --all -- --check` and push the formatting fixes 👍🏻

**Comment by mriehl** [comment]
> @mriehl Looks like you need to run `cargo fmt --all -- --check` and push the formatting fixes 👍🏻

Oof. I actually ran `cargo fmt` but it changed every file, so I thought there was no formatting. Turns out I still had a `rustfmt.toml` file lying around in my home which explains why it changed everything. I rebased the changes and it should be good now!

> I see that you've tested this with your own dotfiles, soo you're confident and happy it works?

Yup, works perfectly for me, both for AUR and non-AUR packages. I did find out about the issue where it was still installing `pkconf` but this turned out to be due to the incorrect package name I was using.

**Comment by rawkode** [comment]
@mriehl The linter still complains. There's a Justfile target if you have `just` installed.

`just fmt`

**Comment by rawkode** [comment]
Thanks @mriehl !

**Pull request merged**
