### PR TITLE
feat: extend actions with variants and conditionals

### PR DESCRIPTION
**Pull request by felipesere**

### CODE REVIEW

**Comment by rawkode** [comment]
@felipesere Now with koto :)

**Comment by svallory** [comment]
Hey @felipesere, this is awesome! I'm actually using comtrya compiled from your branch :)

I only found one issue so far. Both of the actions below will cause panic with `'Sorry, but we don't have a default provider for Linux OS. Please be explicit when requesting a package installation with `provider: XYZ`.'`

```
  - action: package.install
    where: os.name == "macos"
    names: zsh
    
  - action: package.install
    where: os.name == "linux"
    names: zsh
    provider: 'aptitude'

    variants:
      - where: os.name == "macos"
        names: zsh
```

Also, I'd like to suggest a couple of features:

1. Allow koto modules import at manifest level. With that, we can create koto functions and reuse them in the `where` clause. That can help make manifests much cleaner by allowing us to turn 

```
  - action: package.install
    where: '["Arch Linux", "Manjaro"].contains os.distribution'
    names: zsh
    provider: 'yay'

    variants:
      - where: '["Debian", "Linux Mint", "Pop!_OS", "Ubuntu"].contains os.distribution'
        names: zsh
        provider: 'aptitude'

      - where: '["DragonFly BSD", "FreeBSD"].contains os.distribution'
        names: zsh
        provider: 'bsdpkg'
```
into
```
from my_utils import is_supported_distro, provider_for

  - action: package.install
    where: is_supported_distro os.distribution
    names: zsh
    provider: '{{ provider_for os.distribution }}'
```

Now that I've written the code, looks like it may be out of the scope of the feature since it requires the import being available in the evaluation inside `provider`'s value

2. Pass a code block to `where` (or a function which returns a boolean)

This would enable more complex conditions

**Comment by svallory** [comment]
I'm back for one more suggestion! How about allowing koto code in `where` to modify environment variables? Here's my use case

```
  - action: package.install
    where: |
      import io.print
      import utils.base_distribution
      
      os.distribution = base_distribution os
      os.family == 'macos'
    names: zsh
    provider: Homebrew

    variants:
      - where: os.distribution == "debian"
        names: zsh
        provider: aptitude

      - where: os.distribution == "arch"
        names: zsh
        provider: yay
```

Adding new variables to the environment would be even better because then would be able to create `os.pkg_manager` and the number of variants would be greatly reduced

**Comment by rawkode** [comment]
> Hey @felipesere, this is awesome! I'm actually using comtrya compiled from your branch :)
> 
> I only found one issue so far. Both of the actions below will cause panic with `'Sorry, but we don't have a default provider for Linux OS. Please be explicit when requesting a package installation with `provider: XYZ`.'`
> 
> ```
>   - action: package.install
>     where: os.name == "macos"
>     names: zsh
>     
>   - action: package.install
>     where: os.name == "linux"
>     names: zsh
>     provider: 'aptitude'
> 
>     variants:
>       - where: os.name == "macos"
>         names: zsh
> ```
> 

This looks like a bug with the variant merge, I'll get this fixed.


> Also, I'd like to suggest a couple of features:
> 
> 1. Allow koto modules import at manifest level. With that, we can create koto functions and reuse them in the `where` clause. That can help make manifests much cleaner by allowing us to turn
> 
> ```
>   - action: package.install
>     where: '["Arch Linux", "Manjaro"].contains os.distribution'
>     names: zsh
>     provider: 'yay'
> 
>     variants:
>       - where: '["Debian", "Linux Mint", "Pop!_OS", "Ubuntu"].contains os.distribution'
>         names: zsh
>         provider: 'aptitude'
> 
>       - where: '["DragonFly BSD", "FreeBSD"].contains os.distribution'
>         names: zsh
>         provider: 'bsdpkg'
> ```
> 
> into
> 
> ```
> from my_utils import is_supported_distro, provider_for
> 
>   - action: package.install
>     where: is_supported_distro os.distribution
>     names: zsh
>     provider: '{{ provider_for os.distribution }}'
> ```
> 
> Now that I've written the code, looks like it may be out of the scope of the feature since it requires the import being available in the evaluation inside `provider`'s value
> 

I think we could allow these custom function declarations to be loaded during initialisation and provide some .koto loading from a set path {or configured). This could be fun!

> ~2. Pass a code block to `where` (or a function which returns a boolean)~
> 
> ~This would enable more complex conditions~
> 
> Edit: I just figured out blocks actually work! (I was writing the wrong yaml, that's all). And since import works, that will also take care of most of suggestion n. 1 :)
> 
> Here's an example for yaml newbies like myself:
> 
> ```
> actions:
>   - action: command.run
>     where: |
>       import io.print
> 
>       print "Hello from koto"
>       true
>     command: echo
>     args: [HelloCom]
> ```
> 
> output:
> 
> ```
> svallory@Boomerang:~/.dotfiles$ ./bcomtrya ./manifests/ --dry-run -m koto
> Hello from koto
>   INFO manifest_run{manifest="koto"}: Step: RunCommand with privileged false: echo HelloCom (Not printing initializers and finalizers yet)
> ```

Very cool!

**Comment by rawkode** [comment]
OK. I've submitted a few fixes for `os_info` and the `serde` bug ([flatten and alias(https://github.com/serde-rs/serde/issues/1504])

I'm going to get this merged and released, we can increment from here on out.

**Pull request merged**
