### PR TITLE
feat: initial build of github releases support

### LINKED ISSUE #24: New Action: Install GitHub Release Binaries

### PR DESCRIPTION
**Pull request by rawkode**
This really needs some integration tests, so I'm going to take a look at something @icepuma shared recently: 

https://github.com/aelsabbahy/goss

I'm also not super keen on `directory: /usr/local/bin` being mandatory and I think we can be smarter about this by peeking into `${PATH}` for a XDG `/bin` directory or `/usr/local` when missing. Curious what BSD users would expect here too, cc @kraileth and @martintc 

Though this PR is available for testing

Closes #24

### CODE REVIEW

**Comment by rawkode** [comment]
cc @vielmetti @bketelsen

**Review by icepuma — COMMENTED** [review]
One comment and some `clippy` warnings.

**Comment by martintc** [comment]
BSD users have a tendency to be a little more strict to sticking to the prescribed hierarchy of files. Best way to get a feel for it is to read the man pages for hier. On NetBSD, I don't think I've ever set up a `/usr/local/bin` folder. Usually packages added to a NetBSD system using pkgin or pkgsrc, all packages install to `/usr/pkg/bin`. However this is more specific for how NetBSD feels is best to organize files. I don't run FreeBSD often, @kraileth is more the expert on how things happen on FreeBSD, but if I recall, FreeBSD leans more on using `/usr/local.`

**Comment by rawkode** [comment]
@icepuma @martintc Ready for review

**Review by martintc — APPROVED** [review]
Looks good on my end. I do have one comment regarding checking os_info::Bitness. It is reasonable to assume that any machine that doesn't return Bitness:X32 would be 64-bit. But there are some linux distros that os_info will report back wrongly and we can get a different Bitness or just Bitness::Unknown. I doubt we will be getting a Bitness::Unknown from someone running comtrya on their hacked commodore running linux. 

If you think adding a branch for this is unnecessary, your good to merge on my end.

**Comment by icepuma** [comment]
I'll add my review later

**Review by icepuma — APPROVED** [review]

**Comment by icepuma** [comment]
Should we add a checksum check?

```yaml
actions:
  - action: binary.github
    name: comtrya
    directory: /tmp
    repository: comtrya/comtrya
    checksum_file: comtrya.sha512
```

This would be optional. If `checksum_file` is present, we try to download the `checksum_file`. If the file is present we have to create the checksum of the binary and check it against the content of the `checksum_file`.

> Totally optional for this PR

**Pull request merged**
