### PR TITLE
[chore] bump dependencies

### PR DESCRIPTION
**Pull request by icepuma**

### CODE REVIEW

**Comment by rawkode** [comment]
@icepuma This is doing a whole lot more than bumping dependencies. Can you provide some context, please?

**Comment by icepuma** [comment]
Yeah. Sure, when I bump dependencies I usually run `cargo fmt` and `cargo clippy` to see if the bump impacts those in a way. I can adjust the commit accordingly?

**Comment by rawkode** [comment]
@icepuma Ah, these were automated changes. If the tests pass, I'm good. Thank you

**Comment by icepuma** [comment]
I have to thank for the awesome tool you wrote!

**Pull request merged**
