### PR TITLE
contexts command

### PR DESCRIPTION
**Pull request by icepuma**
## I'm submitting a

- [ ] bug fix
- [x] feature
- [ ] documentation addition

### CODE REVIEW

**Comment by rawkode** [comment]
@icepuma What do you think about hiding the `env` context behind an extra flag, such as `contexts --include-env` ?

**Comment by icepuma** [comment]
Why? Too much output? We could truncate the lines to let's say `100` chars.

I don't really like a specific filter for dynamic envs.

**Comment by rawkode** [comment]
My thoughts are that people can run `env` to see their environment variables, they don't need `comtrya contexts` for that and we should ensure we only show them useful information.

`comtrya contexts` could show

```
env:
-- hidden by default, add `--include-env` to display

os:
..

variables:
..
```

**Comment by icepuma** [comment]
```shell
❯ cargo run --bin=comtrya -- contexts 
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/comtrya contexts`
This command is a BETA feature. If you have any feedback: https://github.com/comtrya/comtrya/issues/304

env
 BROWSER              CARGO                               CARGO_HOME                CARGO_MANIFEST_DIR       CARGO_PKG_AUTHORS      CARGO_PKG_DESCRIPTION  
 CARGO_PKG_HOMEPAGE   CARGO_PKG_LICENSE                   CARGO_PKG_LICENSE_FILE    CARGO_PKG_NAME           CARGO_PKG_REPOSITORY   CARGO_PKG_RUST_VERSION 
 CARGO_PKG_VERSION    CARGO_PKG_VERSION_MAJOR             CARGO_PKG_VERSION_MINOR   CARGO_PKG_VERSION_PATCH  CARGO_PKG_VERSION_PRE  COLORTERM              
 CONDA_EXE            CONDA_SHLVL                         DBUS_SESSION_BUS_ADDRESS  DEBUGINFOD_URLS          DESKTOP_SESSION        DESKTOP_STARTUP_ID     
 DISPLAY              EDITOR                              GDMSESSION                GRADLE_HOME              GTK2_RC_FILES          GTK3_MODULES           
 GTK_MODULES          HAXE_STD_PATH                       HOME                      I3SOCK                   JAVA_HOME              KITTY_INSTALLATION_DIR 
 KITTY_PID            KITTY_PUBLIC_KEY                    KITTY_WINDOW_ID           LANG                     LC_ADDRESS             LC_IDENTIFICATION      
 LC_MEASUREMENT       LC_MONETARY                         LC_NAME                   LC_NUMERIC               LC_PAPER               LC_TELEPHONE           
 LC_TIME              LD_LIBRARY_PATH                     LESS_TERMCAP_mb           LESS_TERMCAP_md          LESS_TERMCAP_me        LESS_TERMCAP_se        
 LESS_TERMCAP_so      LESS_TERMCAP_ue                     LESS_TERMCAP_us           LOGNAME                  LS_COLORS              MAIL                   
 MOTD_SHOWN           NEON_DATABASE_URL                   OLDPWD                    OPENAI_API_KEY           PAGER                  PATH                   
 PWD                  QT_QPA_PLATFORMTHEME                RUSTUP_HOME               RUSTUP_TOOLCHAIN         RUST_RECURSION_COUNT   SHELL                  
 SHLVL                SHOW_AND_TELL_EDGE_DB_GITHUB_TOKEN  SSH_AUTH_SOCK             SSL_CERT_DIR             SSL_CERT_FILE          STARSHIP_SESSION_KEY   
 STARSHIP_SHELL       TERM                                TERMINFO                  USER                     WINDOWID               XAUTHORITY             
 XDG_CURRENT_DESKTOP  XDG_DATA_DIRS                       XDG_GREETER_DATA_DIR      XDG_RUNTIME_DIR          XDG_SEAT               XDG_SEAT_PATH          
 XDG_SESSION_CLASS    XDG_SESSION_DESKTOP                 XDG_SESSION_ID            XDG_SESSION_PATH         XDG_SESSION_TYPE       XDG_VTNR               
 _                                                                                                                                                         

include_variables
 <empty> 

os
 bitness      
 codename     
 distribution 
 edition      
 family       
 hostname     
 name         
 version      

user
 config_dir 
 home_dir   
 id         
 name       
 username   

variables
 <empty> 
```

**Review by rawkode — APPROVED** [review]

**Pull request merged**
